version: '2'
services:
    hospital-mysql:
        container_name: hospital-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/hospital/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=hospital
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
